title: Ragavendra Nagraj # your name (or website title) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Software Developer<br>Programmer<br>Performance Engineer<br>Software Developer in Test<br>Security Testing<br><br>
  <a href="https://www.linkedin.com/in/ragavendrabn/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-7J9CY6WCBE # your Google Analytics tracking ID here
